service: rekognition-play
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
functions:
  file-info:
    handler: handler.info
    events:
      - http:
          path: info
          method: get
